### ISSUE TITLE
Інтеграція з Home Assistant

### ISSUE THREAD

**Issue by horodynskyimarian** [denysdovhan/chernivtsi-outages#1]
Доброго дня. Мені потрібно інтегрувати графіки відключень в Home Assistant але як це зробити? Пробував додавати через HACS не вийшло.

**Comment by denysdovhan** [comment]
Цей репозиторій не оновлюється. Скоріш за все структура даних вже змінилась і він більше вже не актуальний.

Для відключень від Yasno можете подивитись ось сюди: https://github.com/denysdovhan/ha-yasno-outages

Для інших міст, в тому числі Чернівців, можна форкнути та взяти код цієї інтеграції за основу. Подібно до того як це зробили: https://github.com/tsdaemon/ha-lviv-poweroff
